"""empty message

Revision ID: 5b1d917b7384
Revises: 123ed342ab81
Create Date: 2020-05-11 13:17:04.085253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1d917b7384'
down_revision = '123ed342ab81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'artists', ['name', 'city', 'state', 'phone', 'website'])
    op.create_unique_constraint(None, 'venues', ['name', 'city', 'state', 'address', 'phone', 'website'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
